{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dentalemon.fullname" . }}
  namespace: {{ include "dentalemon.namespace" . }}
  labels:
    {{- include "dentalemon.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
